### ISSUE TITLE
docs: create doc site

### ISSUE THREAD

**Issue by binodnepali** [binodnepali/react-nepali-datetime-picker#1]
Help me create doc site preferably using [docusaurus]( https://docusaurus.io/)

**Comment by slimpotatoboy** [comment]
I want to contribute

**Comment by binodnepali** [comment]
Hi @slimpotatoboy , Thanks for your interest to contribute in this issue. Are you going to use docusaurus for it?

**Comment by slimpotatoboy** [comment]
yeah

**Comment by slimpotatoboy** [comment]
Where can i communicate with you?

**Comment by binodnepali** [comment]
You can ask any questions about this issue here. If you need to discuss changes in the call, please feel free to send me an invite to [Google Meet](https://meet.google.com/) at this email address nepalibinod9@gmail.com. Usually, I am available Saturday or Sunday for the call.

**Comment by slimpotatoboy** [comment]
Sure

**Comment by binodnepali** [comment]
Initially done in this PR #16
