### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Poowerllz** [binodnepali/react-nepali-datetime-picker#2]
Hi!
Your package is so good, but, I need to ask something.
I can install this package in ReactNative?

**Comment by binodnepali** [comment]
@Poowerllz Hey, Thanks for being patience and checking the package. I am not familiar with ReactNative. If you can install [tailwindcss](https://tailwindcss.com/) in ReactNative project. Maybe you could install this package too. Please feel free to fork this repo and share your thought how to support it.
